### PR TITLE
Merge community fork

### PR DESCRIPTION
**Pull request by dlwyatt**
Refer to #1 for original comment history; this PR resubmitted to target the new dev branch.

This contains primarily updates to the Test-xDscResource functionality; other functions in the module are largely left alone.

The PowerShell.org community fork had a number of formatting changes (double quotes to single quotes, whitespace formatting, etc.)  I've tried to keep those changes out of this pull request, to keep the diff as easy to read as possible.

Summary of changes:

- Removed #Requires -RunAsAdministrator. The commands that require Administrator rights already check for it anyway, and this allows the rest of the module to be used from a normal PowerShell session.
- Added support for Enum types (with associated ValueMap)
- Added support for EmbeddedInstances other than MSFT_Credential and MSFT_KeyValuePair
- Fixed parameter name in Test-xDscResource comment-based help to match actual command definition
- Updated Test-xDscResource to use a process block, since it accepts pipeline input.
- Fixed invalid use of try/catch/finally in Test-MockSchema and Test-DscResourceModule
- Updated code related to Common parameters; now handles all common parameters properly based on command metadata.
- Added very basic tests for Test-xDscResource; these need to be fleshed out quite a bit later.

### CODE REVIEW

**Comment by vors** [comment]
@dave please sign up contribution agreement https://cla.microsoft.com/ . This is one-time step for **all Microsoft** repositories. Once it's done, we will be able to merge PR.

**Comment by dlwyatt** [comment]
Done

**Comment by Abhik11** [comment]
Looks good to me. Thanks for your contribution, Dave!

**Comment by vors** [comment]
CLA verified.

**Pull request merged**
