### PR TITLE
Fixed Typo in Verbose output

### PR DESCRIPTION
**Pull request by HiltonGiesenow**
fixed a minor typo in the Verbose output of the tool

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Hi @HiltonGiesenow, this looks good. If you make/push another commit appveyor will recheck this as the failure looks like a problem with the tests (obviously as nothing you did should have failed this).

**Comment by zhenl-microsoft** [comment]
Hi @tysonjhayes, I looked at the test failure and it seems that your previous change that guards re-import of the module no longer works. As you've made that change and have more expertise on that, would you mind taking a further look on the issue? Thanks.

The test first fails at line 7 of xDscResourceDesigner.Tests.ps1 when importing the module at script level, after disabling the import at script level, I see that the test case you add previously also fails.
Describing xDscResourceDesigner 
 [-] Should not error if imported twice 390ms 
   Expected: the expression not to throw an exception. Message was {Cannot add type. The type name 'Microsoft.PowerShell.xDesiredStateConfiguration.DscResourcePropertyAttribute' already exists.}
       from C:\projects\xdscresourcedesigner\xDSCResourceDesigner.psm1:102 char:5
       +     Add-Type -ErrorAction Stop -TypeDefinition @"
       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
   at line: 12 in C:\projects\xdscresourcedesigner\xDscResourceDesigner.Tests.ps1
   12:             { Import-Module $PSScriptRoot\xDscResourceDesigner.psd1 -ErrorAction Stop } | Should Not Throw 
Describing Test-xDscResource

**Comment by tysonjhayes** [comment]
@zhenl-microsoft - Couple of questions.
1) How do you diable the import at a script level? I'll be honest I actually have no idea what that means.
2) Which version of PS/WMF are you running? I'm not able to repro this on my local machine.

**Comment by zhenl-microsoft** [comment]
Hi @tysonjhayes, let me try to put it clear.
No, I am not able to repro it locally either. So all what I have above are the results from appveyor build.
I forked private branch to edit the file and build it on appveyor. By "disabling script level import", I mean commenting out line 7 at xDscResourceDesigner.Tests.ps1 file.
Thanks.

**Comment by tysonjhayes** [comment]
Ok #29 attempts to correct this problem. I was able to get everything to pass at least. :grin:

**Comment by tysonjhayes** [comment]
OK @HiltonGiesenow if you pull in the changes and resubmit your change everything should go through now. Thanks for your patience!

**Pull request closed without merging**
