### PR TITLE
Changes for issue #48 - to make ValidateSet work with string[]

### PR DESCRIPTION
**Pull request by johlju**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdscresourcedesigner/52)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Hi @johlju! Please add your change to the 'Unreleased' section of the README per the [contributing guidelines](https://github.com/PowerShell/DscResource.Kit/blob/master/CONTRIBUTING.md)

**Comment by johlju** [comment]
I have added the change to the 'Unreleased' section of the README. Missed that one. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdscresourcedesigner/52#-:-KGIxpaoaIXDuAJEmE2s:218638236)*

**Comment by johlju** [comment]
*[a discussion](https://reviewable.io:443/reviews/powershell/xdscresourcedesigner/52#-KGJ-tFx0n8WBDoLVMmh:-KGJ-tFyVvcOpBl0reO4:1106906986) (no related file):*
I have added the change to the 'Unreleased' section of the README.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdscresourcedesigner/52)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdscresourcedesigner/52#-:-KGJRcfEOIXRWTyf7cV0:1417088721)*

**Pull request merged**
